apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/dhineshbabuelango/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 31 Dec 2021 11:57:19 IST
        provider: minikube.sigs.k8s.io
        version: v1.24.0
      name: cluster_info
    server: https://192.168.64.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 31 Dec 2021 11:57:19 IST
        provider: minikube.sigs.k8s.io
        version: v1.24.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/dhineshbabuelango/.minikube/profiles/minikube/client.crt
    client-key: /Users/dhineshbabuelango/.minikube/profiles/minikube/client.key