apiVersion: batch/v1
kind: Job
metadata:
  name: filecopy
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: filecopy
        image: dineshelango/copyfiles:31
        command: [ '/bin/sh', '/Scripts/bin/filecopy.sh' ]
        volumeMounts:
        - mountPath: /filecopy
          name: tmp-volume
      volumes:
      - name: tmp-volume
        persistentVolumeClaim:
          claimName: kb-pv
      restartPolicy: Never